"""empty message

Revision ID: b1757e0da370
Revises: 
Create Date: 2023-12-12 19:46:46.790167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1757e0da370'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses'))
    )
    op.create_table('erc20_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=42), nullable=False),
    sa.Column('source_code', sa.String(), nullable=False),
    sa.Column('is_erc20', sa.Boolean(), nullable=False),
    sa.Column('erc20_version', sa.String(length=255), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_erc20_contracts_status_id_statuses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erc20_contracts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('erc20_contracts')
    op.drop_table('statuses')
    # ### end Alembic commands ###
